version: "3.8"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db

    php:
        build: .
        volumes:
            - ./code:/var/www/html
        links:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: web
        ports:
            - "6603:3306"
        volumes:
            - ./mysql-init:/docker-entrypoint-initdb.d
